on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 24
      - name: Setup npm
        working-directory: ${{ runner.temp }}
        run: npm install --global npm@11.17.0
      - name: Install
        run: npm i
      - name: Test
        run: npm t
      - name: Notify release failure
        if: ${{ failure() }}
        env:
          WEBHOOK_URI: ${{ secrets.WEBHOOK_API_URI }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          jq -n --arg text "Unit-test of code-integrity-actions failed: $RUN_URL" '{text: $text}' |
            curl --fail --silent --show-error \
              --header 'Content-Type: application/json' \
              --data-binary @- "$WEBHOOK_URI"


  protect-e2e-tests:
    runs-on: ubuntu-latest
    name: Protect e2e Test
    environment: production
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 24
      - name: Setup npm
        working-directory: ${{ runner.temp }}
        run: npm install --global npm@11.17.0
      - name: Install and Build
        run: npm i && npm run build
      - name: Test
        id: jscrambler
        uses: ./protect
        with:
          application-id: ${{ secrets.JSCRAMBLER_APPLICATION_ID }}
          secret-key: ${{ secrets.JSCRAMBLER_SECRET_KEY }}
          access-key: ${{ secrets.JSCRAMBLER_ACCESS_KEY }}
          jscrambler-config-path: jscrambler.json
          files-src: |
            protect/src/utils/__tests__/fixtures/*.js
          files-dest: protect/src/utils/__tests__/fixtures-obfuscated/
          source-maps: true
          source-maps-output-path: protect/src/utils/__tests__/fixtures-extra/
          symbol-table-output-path: protect/src/utils/__tests__/fixtures-extra/symbols/
      - name: Check protection-id
        if: "${{ steps.jscrambler.outputs.protection-id == '' }}"
        run: exit 1
      - name: Check Generated Files
        uses: andstor/file-existence-action@20b4d2e596410855db8f9ca21e96fbe18e12930b # v2
        with:
          files: "protect/src/utils/__tests__/fixtures-obfuscated/protect/src/utils/__tests__/fixtures/*.js, protect/src/utils/__tests__/fixtures-extra/jscramblerSourceMaps/protect/src/utils/__tests__/fixtures/*.js.map, protect/src/utils/__tests__/fixtures-extra/symbols/*_symbolTable.json"
          fail: true
          # - name: Upload source maps
          #  uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
          #  with:
          #    name: source-maps
          #    path: protect/dist-extra/jscramblerSourceMaps/
          #    retention-days: 1
      - name: Notify release failure
        if: ${{ failure() }}
        env:
          WEBHOOK_URI: ${{ secrets.WEBHOOK_API_URI }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          jq -n --arg text "E2E tests of code-integrity-actions failed: $RUN_URL" '{text: $text}' |
            curl --fail --silent --show-error \
              --header 'Content-Type: application/json' \
              --data-binary @- "$WEBHOOK_URI"


  create-tag:
    name: Create Jscrambler Version Tag
    runs-on: ubuntu-latest
    needs: [ unit-tests, protect-e2e-tests ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get Access Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@dad2b81e50ce3edeb5f3b7ffbd79f731368bd668
        with:
          application_id: ${{ secrets.CODE_INTEGRITY_ACTIONS_APP_ID }}
          application_private_key: ${{ secrets.CODE_INTEGRITY_ACTIONS_PRIVATE_KEY }}
      - name: Checkout Code Integrity Actions Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: jscrambler/code-integrity-actions
          token: ${{ steps.get_workflow_token.outputs.token }}
          ref: ${{ github.sha }}
      - name: Get Jscrambler CLI Version
        id: dependency_jscrambler
        uses: ActionsTools/read-json-action@9750aa7419d36b6bdc275883f2ecb4d2fdf0db2c # main
        with:
          file_path: "package.json"
          prop_path: "dependencies.jscrambler"
      - name: Create and Push Version Tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ steps.get_workflow_token.outputs.token }}
          custom_tag: ${{ steps.dependency_jscrambler.outputs.value }}
          tag_prefix: v
          release_branches: main
          fetch_all_tags: true
      - name: Notify release failure
        if: ${{ failure() }}
        env:
          WEBHOOK_URI: ${{ secrets.WEBHOOK_API_URI }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          jq -n --arg text "Create git tag on code-integrity-actions failed: $RUN_URL" '{text: $text}' |
            curl --fail --silent --show-error \
              --header 'Content-Type: application/json' \
              --data-binary @- "$WEBHOOK_URI"

